Upstreamify profiles (#2765)
* add Arc capes DNS injector

* Bug fix: Arc DNS injector breaks on Java 17

Error:
Failed to inject cache!
java.lang.reflect.InaccessibleObjectException: Unable to make java.net.InetAddress$CachedAddresses(java.lang.String,java.net.InetAddress[],long) accessible: module java.base does not "opens java.net" to unnamed module @4157f54e

* Validate assets even if it’s fully downloaded (#2730)

* Update MinecraftDownloaderTask.java

Co-authored-by: Duy Tran Khanh <40482367+khanhduytran0@users.noreply.github.com>