Fix a NPE when windowAttribs.get() = null
java.lang.NullPointerException: Cannot invoke "java.lang.Integer.intValue()" because the return value of "java.util.Map.get(Object)" is null
    at org.lwjgl.glfw.GLFW.glfwGetWindowAttrib(GLFW.java:895)